language: python
python:
 - "3.4"

install: "pip install -r requirements.txt"

before_script: "cd gocd2gmail2slack/"

script:
 - "coverage run --source=gocd2gmail2slack -m unittest"

after_success: "coveralls"
