language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"

install: "pip install -r requirements.txt"

before_script: "cd gocd2gmail2slack/"

script:
 - "coverage run -m unittest"

after_success: "coveralls"
